Ward-Group/Ward_Server

- src/main/java/com/ward/ward_server/api/entry/controller/EntryController.java
- src/main/java/com/ward/ward_server/api/entry/controller/EntryRequestDTO.java
- src/main/java/com/ward/ward_server/api/entry/domain/EntryRecord.java
- src/main/java/com/ward/ward_server/api/entry/dto/EntryRecordDTO.java
- src/main/java/com/ward/ward_server/api/entry/repository/EntryRepository.java
- src/main/java/com/ward/ward_server/api/entry/service/EntryService.java
- src/main/java/com/ward/ward_server/api/user/controller/AuthController.java
- src/main/java/com/ward/ward_server/api/user/entity/User.java
- src/main/java/com/ward/ward_server/api/user/entity/UserEntity.java
- src/main/java/com/ward/ward_server/api/user/repository/UserRepository.java
- src/main/java/com/ward/ward_server/api/user/service/AuthService.java
- src/main/java/com/ward/ward_server/api/user/service/UserService.java
- src/main/java/com/ward/ward_server/api/webcrawling/dto/ItemDTO.java
- src/main/java/com/ward/ward_server/api/webcrawling/entity/Item.java
- src/main/java/com/ward/ward_server/global/exception/ExceptionCode.java
응모 내역 기능
패치조인, DTO 활용하여 N+1 최적화
> Feature/entry record 응모 내역 기능 추가

- src/main/java/com/ward/ward_server/api/entry/controller/EntryController.java
- src/main/java/com/ward/ward_server/api/entry/domain/EntryRecord.java
- src/main/java/com/ward/ward_server/api/entry/dto/EntryRecordDTO.java
- src/main/java/com/ward/ward_server/api/entry/service/EntryService.java
- src/main/java/com/ward/ward_server/api/item/controller/ItemController.java
- src/main/java/com/ward/ward_server/api/item/controller/ItemRequsetDTO.java
- src/main/java/com/ward/ward_server/api/item/controller/WebCrawlingController.java
- src/main/java/com/ward/ward_server/api/item/dto/ItemDTO.java
- src/main/java/com/ward/ward_server/api/item/dto/ItemResponseDTO.java
- src/main/java/com/ward/ward_server/api/item/dto/WebProductData.java
- src/main/java/com/ward/ward_server/api/item/entity/Item.java
- src/main/java/com/ward/ward_server/api/item/entity/enumtype/Brand.java
- src/main/java/com/ward/ward_server/api/item/entity/enumtype/State.java
- src/main/java/com/ward/ward_server/api/item/entity/enumtype/converter/BrandConverter.java
- src/main/java/com/ward/ward_server/api/item/repository/ItemRepository.java
- src/main/java/com/ward/ward_server/api/item/service/ItemService.java
- src/main/java/com/ward/ward_server/api/item/service/WebCrawlingService.java
- src/main/java/com/ward/ward_server/api/item/webCrawler/KasinaWebCrawler.java
- src/main/java/com/ward/ward_server/api/item/webCrawler/NikeWebCrawler.java
- src/main/java/com/ward/ward_server/api/webcrawling/entity/enumtype/State.java
- src/test/java/com/ward/ward_server/webcrawling/KasinaWebCrawlerTest.java
- src/test/java/com/ward/ward_server/webcrawling/NikeWebCrawlerTest.java
응모 내역 1건 응모 여부 확인+Item 1건 상세 페이지
item 1건 상세 페이지는 로그인 시 응모 여부까지 확인
> Feature/entry record 응모 내역 1건 응모 여부 확인+Item 1건 상세 페이지

- src/main/java/com/ward/ward_server/api/entry/controller/EntryController.java
- src/main/java/com/ward/ward_server/api/entry/repository/EntryRepository.java
- src/main/java/com/ward/ward_server/api/entry/service/EntryService.java
- src/main/java/com/ward/ward_server/api/item/controller/ItemController.java
- src/main/java/com/ward/ward_server/api/item/service/ItemService.java
- src/main/java/com/ward/ward_server/global/exception/ExceptionCode.java
userId, ItemId 받아서 응모 내역 1건 삭제 기능
> feat: 응모 내역 1건 삭제 기능

- src/main/java/com/ward/ward_server/api/item/entity/Item.java
- src/main/java/com/ward/ward_server/api/user/entity/User.java
- src/main/java/com/ward/ward_server/api/wishlist/controller/WishlistController.java
- src/main/java/com/ward/ward_server/api/wishlist/domain/Wishlist.java
- src/main/java/com/ward/ward_server/api/wishlist/repository/WishlistRepository.java
- src/main/java/com/ward/ward_server/api/wishlist/service/WishlistService.java
Entity 를 user, item 과 연관 관계 매핑 완료
> feat: 관심 목록 기본 틀 잡고 Entity 연관관계 매핑 완료

- src/main/java/com/ward/ward_server/api/entry/controller/EntryController.java
- src/main/java/com/ward/ward_server/api/entry/dto/EntryRecordResponseDTO.java
- src/main/java/com/ward/ward_server/api/entry/dto/EntryRequestDTO.java
- src/main/java/com/ward/ward_server/api/entry/service/EntryService.java
- src/main/java/com/ward/ward_server/api/wishlist/controller/WishlistController.java
- src/main/java/com/ward/ward_server/api/wishlist/dto/WishlistRequestDTO.java
- src/main/java/com/ward/ward_server/api/wishlist/repository/WishlistRepository.java
- src/main/java/com/ward/ward_server/api/wishlist/service/WishlistService.java
- src/main/java/com/ward/ward_server/global/exception/ExceptionCode.java
> feat: 관심 목록 추가 기능 구현

- src/main/java/com/ward/ward_server/api/wishlist/controller/WishlistController.java
- src/main/java/com/ward/ward_server/api/wishlist/repository/WishlistRepository.java
- src/main/java/com/ward/ward_server/api/wishlist/service/WishlistService.java
- src/main/java/com/ward/ward_server/global/exception/ExceptionCode.java
> feat: 관심 목록 삭제 기능 구현

- src/main/java/com/ward/ward_server/api/item/entity/Item.java
- src/main/java/com/ward/ward_server/api/user/controller/AuthController.java
- src/main/java/com/ward/ward_server/api/user/dto/RegisterRequest.java
- src/main/java/com/ward/ward_server/api/user/entity/User.java
- src/main/java/com/ward/ward_server/api/user/service/AuthService.java
회원 가입 시 닉네임 필수 입력으로 바뀌어 회원가입 요청 시 데이터 전달 받음.
> feat: User 엔티티, registerRequestDTO nickname 추가

- src/main/java/com/ward/ward_server/api/user/controller/AuthController.java
- src/main/java/com/ward/ward_server/api/user/entity/User.java
- src/main/java/com/ward/ward_server/api/user/service/UserService.java
> feat: 관리자/사용자 권한 부여 기능 추가

- src/main/java/com/ward/ward_server/api/user/controller/AuthController.java
- src/main/java/com/ward/ward_server/api/user/entity/User.java
- src/main/java/com/ward/ward_server/api/user/repository/UserRepository.java
- src/main/java/com/ward/ward_server/api/user/service/AuthService.java
컨트롤러,서비스,레포지토리 작성.
User entity 에서 nickname unique= true, nullable = false 로 변경
> feat: 사용자 닉네임 중복 체크 기능

- src/main/java/com/ward/ward_server/api/user/auth/security/JwtIssuer.java
email -> e 로 변경
이 변경으로 principal 에서 email 도 가져올 수 있습니다.
> style: jwt token 디코딩 했을 때 표기 방법 변경

- src/main/java/com/ward/ward_server/api/user/auth/security/UnauthorizedHandler.java
- src/main/java/com/ward/ward_server/api/user/controller/AuthController.java
- src/main/java/com/ward/ward_server/api/user/entity/RefreshToken.java
- src/main/java/com/ward/ward_server/api/user/entity/User.java
- src/main/java/com/ward/ward_server/api/user/repository/RefreshTokenRepository.java
- src/main/java/com/ward/ward_server/api/user/repository/UserRepository.java
- src/main/java/com/ward/ward_server/api/user/service/AuthService.java
- src/main/java/com/ward/ward_server/api/user/service/RefreshTokenService.java
- src/main/java/com/ward/ward_server/global/exception/handler/ExceptionHandler.java
RefreshToken 을 분리하여 다중 기기 지원 관리가 가능하도록 한다.
refreshtoken 을 invalid 처리하여 access token 재발급이 안되도록 로그아웃 기능 구현
> feature: RefreshToken 엔티티 분리 + 로그아웃 기능

- src/main/java/com/ward/ward_server/api/user/controller/AuthController.java
- src/main/java/com/ward/ward_server/api/user/controller/UserController.java
- src/main/java/com/ward/ward_server/api/user/entity/User.java
- src/main/java/com/ward/ward_server/api/user/repository/UserRepository.java
- src/main/java/com/ward/ward_server/api/user/service/UserService.java
- src/main/java/com/ward/ward_server/global/response/ApiResponseMessage.java
로그인한 회원 닉네임 조회, 수정 기능 개발
jwt 토큰 필요
@AuthenticationPrincipal 사용
> feature: 닉네임 조회+닉네임 수정 기능

- src/main/java/com/ward/ward_server/api/user/entity/SocialLogin.java
테이블명 단수로 통일 - 규칙은 아니지만 선호에 따라 단수로 변경
컬럼 명 - 통일성을 위해 삭제
> refactor: SocialLogin.java 에서 @Table, @Column 어노테이션 삭제

- src/main/java/com/ward/ward_server/api/user/service/AuthService.java
- src/main/java/com/ward/ward_server/global/exception/ExceptionCode.java
api 명세서 작성하며 부족한 예외처리 보완하였습니다.
> refactor: 토큰 갱신 메서드 예외처리 추가

- src/main/java/com/ward/ward_server/api/user/entity/SocialLogin.java
providerId 기본값(255)->1000 으로 설정
> fix: 회원가입 시 providerId 길이로 인한 실패 해결

- src/main/java/com/ward/ward_server/api/user/controller/AppleUserController.java
- src/main/java/com/ward/ward_server/api/user/controller/AuthController.java
- src/main/java/com/ward/ward_server/api/user/dto/AddSocialLoginRequest.java
- src/main/java/com/ward/ward_server/api/user/dto/LoginRequest.java
- src/main/java/com/ward/ward_server/api/user/dto/RegisterRequest.java
- src/main/java/com/ward/ward_server/api/user/dto/UserInfoUpdateRequest.java
- src/main/java/com/ward/ward_server/api/user/service/AuthService.java
프로젝트 규칙에 따라 java14 이상에서 지원하는 record 사용
그에 따른 controller, service 단 코드 수정
> refactor: dto 클래스->record 로 변경

- src/main/java/com/ward/ward_server/api/user/auth/security/JwtAuthenticationFilter.java
- src/main/java/com/ward/ward_server/api/user/auth/security/JwtDecoder.java
- src/main/java/com/ward/ward_server/api/user/auth/security/UnauthorizedHandler.java
- src/main/java/com/ward/ward_server/api/user/service/AuthService.java
- src/main/java/com/ward/ward_server/global/config/WebSecurityConfig.java
- src/main/java/com/ward/ward_server/global/exception/ExceptionCode.java
access, refresh 토큰 누락과 만료 예외 처리 구체화
> refactor: 예외 처리 구체화-access, refresh 토큰

- src/main/java/com/ward/ward_server/api/entry/service/EntryRecordService.java
- src/main/java/com/ward/ward_server/api/item/repository/ItemRepository.java
- src/main/java/com/ward/ward_server/api/releaseInfo/controller/ReleaseInfoController.java
- src/main/java/com/ward/ward_server/api/releaseInfo/dto/ReleaseInfoDetailResponse.java
- src/main/java/com/ward/ward_server/api/releaseInfo/dto/ReleaseInfoIdentificationRequest.java
- src/main/java/com/ward/ward_server/api/releaseInfo/dto/ReleaseInfoRequest.java
- src/main/java/com/ward/ward_server/api/releaseInfo/dto/ReleaseInfoSimpleResponse.java
- src/main/java/com/ward/ward_server/api/releaseInfo/entity/ReleaseInfo.java
- src/main/java/com/ward/ward_server/api/releaseInfo/entity/enums/CurrencyUnit.java
- src/main/java/com/ward/ward_server/api/releaseInfo/entity/enums/DeliveryMethod.java
- src/main/java/com/ward/ward_server/api/releaseInfo/entity/enums/NotificationMethod.java
- src/main/java/com/ward/ward_server/api/releaseInfo/entity/enums/ReleaseMethod.java
- src/main/java/com/ward/ward_server/api/releaseInfo/service/ReleaseInfoService.java
- src/main/java/com/ward/ward_server/global/config/WebSecurityConfig.java
- src/main/java/com/ward/ward_server/global/exception/handler/ExceptionHandler.java
- src/main/java/com/ward/ward_server/global/response/error/ErrorCode.java
- src/test/java/com/ward/ward_server/api/item/repository/ItemRepositoryTest.java
1. status 칼럼 삭제
2. 벌매가 release price, 화폐단위 currency unit 칼럼 추가
3. 관련 로직 수정
4. 발매정보 상세조회 dto 수정
> 발매정보 release info 엔티티 칼럼 추가 및 관련 로직 수정

- src/main/java/com/ward/ward_server/api/releaseInfo/controller/ReleaseInfoController.java
- src/main/java/com/ward/ward_server/api/releaseInfo/dto/ItemIdentifier.java
- src/main/java/com/ward/ward_server/api/releaseInfo/dto/ReleaseInfoIdentifierRequest.java
1. ReleaseInfoIdentificationRequest -> ItemIdentifier 으로 수정
2. 다중 request body 구현
> request body 다중 입력 구현

- src/main/java/com/ward/ward_server/api/search/controller/SearchHistoryController.java
- src/main/java/com/ward/ward_server/api/search/entity/SearchHistory.java
- src/main/java/com/ward/ward_server/api/search/repository/SearchHistoryRepository.java
- src/main/java/com/ward/ward_server/api/search/service/SearchHistoryService.java
- @AuthenticationPrincipal 에서 userId 가져와서 검색 기록 조회
- 검색어 길이 제한하여 불필요한 데이터 저장 방지
> feature: <검색 화면> - 검색 기록 조회 API 개발

- src/main/java/com/ward/ward_server/global/exception/handler/ExceptionHandler.java
- src/main/java/com/ward/ward_server/global/response/error/ErrorMessage.java
잘못된 URL로 요청시 NOT_FOUND 응답해주는 예외처리 구현
646f21b4804ffe1c40a24a18acb0d09637396e30
1. 예외처리 핸들러를 추가 및 적용했습니다.
2. 에러 메세지를 작성했습니다.
- Close #75
> Feat: not found 예외처리 구현

- src/main/java/com/ward/ward_server/api/item/service/ItemService.java
오늘 마감 상품 api 차단 해제 
1a5ee7788f202ada48a0f8f455292da9acdae326
서비스 단계에서 차단해놨던 구분을 해제했습니다.
- Close #91
> Fix: 오늘 마감 상품 api 차단 해제

- src/main/java/com/ward/ward_server/api/user/service/AuthService.java
- src/main/java/com/ward/ward_server/api/user/service/UserService.java
- src/main/java/com/ward/ward_server/global/exception/ExceptionCode.java
- src/main/java/com/ward/ward_server/global/util/ValidationUtils.java
닉네임 조건 추가
- 닉네임 조건
1) 필수 입력
2) 중복된 닉네임 사용 불가
3) 한글/영문/숫자만 입력 가능
4) 최대 8자까지 입력 가능
* 텍스트 입력 전 플레이스홀더 문구:
사용할 닉네임을 입력해 주세요.
* 에러 메시지
1) 미입력 시: 필수 입력 사항입니다.
2) 중복될 경우: 이미 사용중인 닉네임입니다.
3) 한글/영문/숫자 외 입력 시: 한글/영문/숫자만 입력 가능합니다.
4) 글자수 초과 시: 최대 8자까지 작성 가능합니다.
* 닉네임 조건 충족 시 안내 문구:
사용 가능한 닉네임입니다.
- Close #이슈번호
> feat: 닉네임 조건 추가(회원가입, 닉네임 변경 시)

- .github/workflows/ci-cd-prpeline.yml
Add CI/CD pipeline workflow
- Close #이슈번호
> Add CI/CD pipeline workflow

- src/test/java/com/ward/ward_server/api/item/repository/ItemRepositoryTest.java
- src/test/java/com/ward/ward_server/api/releaseInfo/repository/ReleaseInfoRepositoryTest.java
- src/test/java/com/ward/ward_server/controller/HelloControllerTest.java
cicd 확인을 위해 실패하는 테스트 주석처리
- Close #이슈번호
> test: cicd 확인을 위해 실패하는 테스트 주석처리

- src/test/java/com/ward/ward_server/api/item/entity/enumtype/SectionTest.java
- src/test/java/com/ward/ward_server/api/item/repository/BrandRepositoryTest.java
- src/test/java/com/ward/ward_server/api/item/repository/ItemRepositoryTest.java
- src/test/java/com/ward/ward_server/api/item/service/BrandServiceTest.java
- src/test/java/com/ward/ward_server/api/item/service/ItemServiceTest.java
- src/test/java/com/ward/ward_server/api/releaseInfo/repository/ReleaseInfoRepositoryTest.java
- src/test/java/com/ward/ward_server/api/releaseInfo/service/ReleaseInfoServiceTest.java
- src/test/java/com/ward/ward_server/api/search/service/SearchServiceTest.java
- src/test/java/com/ward/ward_server/controller/HelloControllerTest.java
- src/test/java/com/ward/ward_server/controller/WithAdminUser.java
- src/test/java/com/ward/ward_server/controller/WithMockUser.java
- src/test/java/com/ward/ward_server/controller/WithMockUserSecurityContextFactory.java
cicd 확인을 위해 실패하는 테스트 주석처리
- Close #이슈번호
> test: cicd 확인을 위해 전체 테스트 주석처리2

- .gitignore
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
> test: cicd 확인을 위해 gitignore 수정/application.yml, application-dev.yml 업로드
